Update CHANGELOG.md
souhail-5/zeed pull request #27
Opened 2023-07-19 03:23 UTC by viktoriussuwandi

**Description**
Hi [souhail-5](https://github.com/souhail-5),
just trying to fix #26, please check it out

**Areas of Concern**
[CHANGELOG.md](https://github.com/souhail-5/zeed/blob/main/CHANGELOG.md)

**TODO**
[Update CHANGELOG.md](https://github.com/souhail-5/zeed/commit/c3906fcfc8303d1949f7e356dcccde7bdb50a31f)

**Dependencies / Relations with other projects**
- None

2023-07-19 21:49 UTC, souhail-5 commented
Hi @viktoriussuwandi 😃 ,

Thank you for your contribution. The notation `LAST_RELEASE_TAG` is a placeholder and not an actual tag. The latest release tag is: `v1.3.0`.

Would you be interested in updating your pull request?

PS: for a more automated approach, I'm considering a change to our GitHub Actions workflow, but we can handle this in another issue.

2023-07-20 01:19 UTC, viktoriussuwandi commented
> Hi @viktoriussuwandi 😃 ,
> 
> Thank you for your contribution. The notation `LAST_RELEASE_TAG` is a placeholder and not an actual tag. The latest release tag is: `v1.3.0`.
> 
> Would you be interested in updating your pull request?
> 
> PS: for a more automated approach, I'm considering a change to our GitHub Actions workflow, but we can handle this in another issue.

sure @souhail-5, `LAST_RELEASE_TAG` updated

2023-07-20 06:36 UTC, souhail-5 requested changes

2023-07-20 06:36 UTC, souhail-5 commented on CHANGELOG.md
> +## [Unreleased](https://github.com/souhail-5/zeed/compare/v1.3.0)
```suggestion
## [Unreleased](https://github.com/souhail-5/zeed/compare/v1.3.0...main)
```

The "Unreleased" section compares the latest tag to the `main` branch 😉.

2023-07-20 07:34 UTC, souhail-5 approved these changes

2023-07-20 07:35 UTC, merged

2023-07-20 07:35 UTC, souhail-5 commented
Thank you for your contribution @viktoriussuwandi ✌️.